version: "3.2"
services:
  server:
    build: './docker/php'
    volumes:
      - ./:/project
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /project
    networks:
      server:
        aliases:
          - project.local
        ipv4_address: 172.16.2.36
      ext:
    ports:
      - "81:80"
    links:
      - phpmyadmin
    stdin_open: true
    tty: true
    privileged: true
  mysql:
    image: mysql:5.7
    networks:
      server:
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    networks:
      server:
    restart: always
    ports:
      - 8800:80
    links:
      - mysql
networks:
  ext:
    external: true
  server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24